document.write('		<!-- 사이드 메뉴 -->');
document.write('		<nav id="sidebar" class="onlyPc">');
document.write('			<div class="inner">');
document.write('				<!-- 로고 & 메뉴 -->');
document.write('				<div class="top_btn_area">');
document.write('					<div class="inner">');
document.write('						<a href="#;" class="el_lotte_ci">');
document.write('							<span class="blind">엘 롯데</span>');
document.write('						</a>');
document.write('						<button class="btn_side_menu">');
document.write('							<span class="blind">주메뉴 열기</span>');
document.write('							<span class="meun_hambuger" aria-hidden="true">');
document.write('								<i class="center_line"></i>');
document.write('							</span>');
document.write('						</button>');
document.write('					</div>');
document.write('				</div>');
document.write('				<!-- 메뉴 -->');
document.write('				<div class="box_side_menu">');
document.write('					<h3 class="blind">수지몰 안내</h3>');
document.write('					<ul class="list_side_basic list_side_menu">');
document.write('						<li>');
document.write('							<div class="side_icon_wrap">');
document.write('								<a href="#;" class="ico_side_menu ico_floor" title="층별 안내">');
document.write('									<span class="blind">층별안내</span>');
document.write('								</a>');
document.write('								<div class="tooltip_side_menu">');
document.write('									<p>자세한 층별 매장 안내 정보를 알려드려요</p>');
document.write('								</div>');
document.write('							</div>');
document.write('						</li>');
document.write('						<li>');
document.write('							<div class="side_icon_wrap">');
document.write('								<a href="#;" class="ico_side_menu ico_map" title="오시는 길 안내">');
document.write('									<span class="blind">오시는 길</span>');
document.write('								</a>');
document.write('								<div class="tooltip_side_menu">');
document.write('									<p>롯데몰 수지로 오시는 길을 알려드려요</p>');
document.write('								</div>');
document.write('							</div>');
document.write('						</li>');
document.write('						<li>');
document.write('							<div class="side_icon_wrap">');
document.write('								<a href="#;" class="ico_side_menu ico_park" title="주차안내">');
document.write('									<span class="blind">주차안내</span>');
document.write('								</a>');
document.write('								<div class="tooltip_side_menu">');
document.write('									<p>주차시설과 요금정보를 확인하세요</p>');
document.write('								</div>');
document.write('							</div>');
document.write('						</li>');
document.write('						<li>');
document.write('							<div class="side_icon_wrap">');
document.write('								<button class="ico_side_menu ico_share" title="SNS 공유하기">');
document.write('									<span class="blind">SNS 공유 목록 열기</span>');
document.write('								</button>');
document.write('								<div class="tooltip_side_menu">');
document.write('									<p>SNS 채널에서도 콘텐츠를 즐겨보세요</p>');
document.write('								</div>');
document.write('							</div>');
document.write('							<!-- SNS 뎁스 -->');
document.write('							<ul class="list_slide_sns list_side_menu">');
document.write('								<li>');
document.write('									<div class="side_icon_wrap">');
document.write('										<button class="ico_side_menu ico_insta" title="인스타그램 공유하기">');
document.write('											<span class="blind">인스타그램 공유하기</span>');
document.write('										</button>');
document.write('										<div class="tooltip_side_menu">');
document.write('											<p>인스타그램 공유</p>');
document.write('										</div>');
document.write('									</div>');
document.write('								</li>');
document.write('								<li>');
document.write('									<div class="side_icon_wrap">');
document.write('										<button class="ico_side_menu ico_blog" title="블로그 공유하기">');
document.write('											<span class="blind">블로그 공유하기</span>');
document.write('										</button>');
document.write('										<div class="tooltip_side_menu">');
document.write('											<p>블로그 공유</p>');
document.write('										</div>');
document.write('									</div>');
document.write('								</li>');
document.write('								<li>');
document.write('									<div class="side_icon_wrap">');
document.write('										<button class="ico_side_menu ico_facebook" title="페북 공유하기">');
document.write('											<span class="blind">페북 공유하기</span>');
document.write('										</button>');
document.write('										<div class="tooltip_side_menu">');
document.write('											<p>페이스북 공유</p>');
document.write('										</div>');
document.write('									</div>');
document.write('								</li>');
document.write('							</ul>');
document.write('						</li>');
document.write('					</ul>');
document.write('				</div>');
document.write('				<!-- 지점안내메뉴 -->');
document.write('				<div class="box_market_list">');
document.write('					<h3 class="blind">지점 안내</h3>');
document.write('					<ul class="list_markt_info">');
document.write('						<li class="first">');
document.write('							<!-- 이름부분 -->');
document.write('							<div class="wrap_market_name">');
document.write('								<strong class="title_market">수지점</strong>');
document.write('								<button class="btn_market_more site_market">');
document.write('									<i aria-hidden="true" class="ico_plus"></i>');
document.write('									<span class="blind">상세내용 보기</span>');
document.write('								</button>');
document.write('							</div>');
document.write('							<!-- 정보영역 -->');
document.write('							<div class="wrap_market_info">');
document.write('								<span aria-hidden="true" class="lotte_name">lotte mall</span>');
document.write('								<h4 class="name_market">롯데몰 수지점</h4>');
document.write('								<div class="info_open_day">');
document.write('									<strong class="blind">오늘 날짜</strong>');
document.write('									<!-- [D] 월과 일 사이의 주석은 남겨주세요-->');
document.write('									<span>06<em class="blind">월</em></span><!--');
document.write('									--><span>/04<em class="blind">일</em></span>');
document.write('									<span class="data_day">(Mon)<em class="blind">월요일</em></span>');
document.write('									<p class="desc_txt">오늘은 정상영업일 입니다.</p>');
document.write('								</div>');
document.write('								<div class="wrap_open_time">');
document.write('									<strong class="title_open_time tc">운영시간</strong>');
document.write('									<ul class="list_open_time">');
document.write('										<li>');
document.write('											<strong>롯데몰</strong>');
document.write('											<p>10 : 30 ~ 22 : 00</p>');
document.write('										</li>');
document.write('										<li>');
document.write('											<strong>롯데마트</strong>');
document.write('											<p>10 : 00 ~ 23 : 00</p>');
document.write('										</li>');
document.write('										<li>');
document.write('											<strong>롯데시네마</strong>');
document.write('											<p>09 : 00 ~ 02 : 00<span>(익일)</span></p>');
document.write('										</li>');
document.write('									</ul>');
document.write('								</div>');
document.write('							</div>');
document.write('						</li>');
document.write('					</ul>');
document.write('					<ul class="list_markt_info type_accodion">');
document.write('						<li class="first">');
document.write('							<div class="wrap_market_info">');
document.write('								<span aria-hidden="true" class="lotte_name">lotte mall</span>');
document.write('								<h4 class="name_market">롯데몰 수지점</h4>');
document.write('								<div class="info_open_day">');
document.write('									<strong class="blind">오늘 날짜</strong>');
document.write('									<!-- [D] 월과 일 사이의 주석은 남겨주세요-->');
document.write('									<span>06<em class="blind">월</em></span><!--');
document.write('									--><span>/04<em class="blind">일</em></span>');
document.write('									<span class="data_day">(Mon)<em class="blind">월요일</em></span>');
document.write('									<p class="desc_txt">오늘은 정상영업일 입니다.</p>');
document.write('								</div>');
document.write('								<div class="wrap_open_time">');
document.write('									<strong class="title_open_time tc">운영시간</strong>');
document.write('									<ul class="list_open_time">');
document.write('										<li>');
document.write('											<strong>롯데몰</strong>');
document.write('											<p>10 : 30 ~ 22 : 00</p>');
document.write('										</li>');
document.write('										<li>');
document.write('											<strong>롯데마트</strong>');
document.write('											<p>10 : 00 ~ 23 : 00</p>');
document.write('										</li>');
document.write('										<li>');
document.write('											<strong>롯데시네마</strong>');
document.write('											<p>09 : 00 ~ 02 : 00<span>(익일)</span></p>');
document.write('										</li>');
document.write('									</ul>');
document.write('								</div>');
document.write('							</div>');
document.write('						</li>');
document.write('						<li>');
document.write('							<!-- 이름 -->');
document.write('							<div class="wrap_market_name">');
document.write('								<strong class="title_market">수원점</strong>');
document.write('								<button class="btn_market_more">');
document.write('									<i aria-hidden="true" class="ico_plus"></i>');
document.write('									<span class="blind">상세내용 보기</span>');
document.write('								</button>');
document.write('							</div>');
document.write('							<!-- 정보 -->');
document.write('							<div class="wrap_market_info">');
document.write('								<span aria-hidden="true" class="lotte_name">lotte mall</span>');
document.write('								<h4 class="name_market">롯데몰 수지점</h4>');
document.write('								<div class="info_open_day">');
document.write('									<strong class="blind">오늘 날짜</strong>');
document.write('									<!-- [D] 월과 일 사이의 주석은 남겨주세요--> ');
document.write('									<span>06<em class="blind">월</em></span><!--');
document.write('									--><span>/04<em class="blind">일</em></span>');
document.write('									<span class="data_day">(Mon)<em class="blind">월요일</em></span>');
document.write('									<p class="desc_txt">오늘은 정상영업일 입니다.</p>');
document.write('								</div>');
document.write('								<div class="wrap_open_time">');
document.write('									<strong class="title_open_time tc">운영시간</strong>');
document.write('									<ul class="list_open_time">');
document.write('										<li>');
document.write('											<strong>롯데몰</strong>');
document.write('											<p>10 : 30 ~ 22 : 00</p>');
document.write('										</li>');
document.write('										<li>');
document.write('											<strong>롯데마트</strong>');
document.write('											<p>10 : 00 ~ 23 : 00</p>');
document.write('										</li>');
document.write('										<li>');
document.write('											<strong>롯데시네마</strong>');
document.write('											<p>09 : 00 ~ 02 : 00<span>(익일)</span></p>');
document.write('										</li>');
document.write('									</ul>');
document.write('									<a href="#;" title="페이지 이동" class="link_visit_site">바로가기</a>');
document.write('								</div>');
document.write('							</div>');
document.write('						</li>');
document.write('						<li>');
document.write('							<!-- 이름 -->');
document.write('							<div class="wrap_market_name">');
document.write('								<strong class="title_market">은평점</strong>');
document.write('								<button class="btn_market_more">');
document.write('									<i aria-hidden="true" class="ico_plus"></i>');
document.write('									<span class="blind">상세내용 보기</span>');
document.write('								</button>');
document.write('							</div>');
document.write('							<!-- 정보 -->');
document.write('							<div class="wrap_market_info">');
document.write('								<span aria-hidden="true" class="lotte_name">lotte mall</span>');
document.write('								<h4 class="name_market">롯데몰 은평점</h4>');
document.write('								<div class="info_open_day">');
document.write('									<strong class="blind">오늘 날짜</strong>');
document.write('									<!-- [D] 월과 일 사이의 주석은 남겨주세요-->');
document.write('									<span>06<em class="blind">월</em></span><!--');
document.write('									--><span>/04<em class="blind">일</em></span>');
document.write('									<span class="data_day">(Mon)<em class="blind">월요일</em></span>');
document.write('									<p class="desc_txt">오늘은 정상영업일 입니다.</p>');
document.write('								</div>');
document.write('								<div class="wrap_open_time">');
document.write('									<strong class="title_open_time tc">운영시간</strong>');
document.write('									<ul class="list_open_time">');
document.write('										<li>');
document.write('											<strong>롯데몰</strong>');
document.write('											<p>10 : 30 ~ 22 : 00</p>');
document.write('										</li>');
document.write('										<li>');
document.write('											<strong>롯데마트</strong>');
document.write('											<p>10 : 00 ~ 23 : 00</p>');
document.write('										</li>');
document.write('										<li>');
document.write('											<strong>롯데시네마</strong>');
document.write('											<p>09 : 00 ~ 02 : 00<span>(익일)</span></p>');
document.write('										</li>');
document.write('									</ul>');
document.write('									<a href="#;" title="페이지 이동" class="link_visit_site">바로가기</a>');
document.write('								</div>');
document.write('							</div>');
document.write('						</li>');
document.write('						<li>');
document.write('							<!-- 이름 -->');
document.write('							<div class="wrap_market_name">');
document.write('								<strong class="title_market">김포공항점</strong>');
document.write('								<button class="btn_market_more">');
document.write('									<i aria-hidden="true" class="ico_plus"></i>');
document.write('									<span class="blind">상세내용 보기</span>');
document.write('								</button>');
document.write('							</div>');
document.write('							<!-- 정보 -->');
document.write('							<div class="wrap_market_info">');
document.write('								<span aria-hidden="true" class="lotte_name">lotte mall</span>');
document.write('								<h4 class="name_market">롯데몰 김포공항점</h4>');
document.write('								<div class="info_open_day">');
document.write('									<strong class="blind">오늘 날짜</strong>');
document.write('									<!-- [D] 월과 일 사이의 주석은 남겨주세요-->');
document.write('									<span>06<em class="blind">월</em></span><!--');
document.write('									--><span>/04<em class="blind">일</em></span>');
document.write('									<span class="data_day">(Mon)<em class="blind">월요일</em></span>');
document.write('									<p class="desc_txt">오늘은 정상영업일 입니다.</p>');
document.write('								</div>');
document.write('								<div class="wrap_open_time">');
document.write('									<strong class="title_open_time tc">운영시간</strong>');
document.write('									<ul class="list_open_time">');
document.write('										<li>');
document.write('											<strong>롯데몰</strong>');
document.write('											<p>10 : 30 ~ 22 : 00</p>');
document.write('										</li>');
document.write('										<li>');
document.write('											<strong>롯데마트</strong>');
document.write('											<p>10 : 00 ~ 23 : 00</p>');
document.write('										</li>');
document.write('										<li>');
document.write('											<strong>롯데시네마</strong>');
document.write('											<p>09 : 00 ~ 02 : 00<span>(익일)</span></p>');
document.write('										</li>');
document.write('									</ul>');
document.write('									<a href="#;" title="페이지 이동" class="link_visit_site">바로가기</a>');
document.write('								</div>');
document.write('							</div>');
document.write('						</li>');
document.write('					</ul>');
document.write('				</div>');
document.write('			</div>');
document.write('			<hr>');
document.write('		</nav>');